#ifndef SQLITE_SCANNER_CORE_DATA_COMPATIBLE
#define SQLITE_SCANNER_CORE_DATA_COMPATIBLE 1
#endif

#ifndef SQLITE_SCANNER_LOG_QUERIES
#define SQLITE_SCANNER_LOG_QUERIES 1
#endif

#ifndef SQLITE_SCANNER_IN_FILTER_PUSHDOWN
#define SQLITE_SCANNER_IN_FILTER_PUSHDOWN 1
#endif
